config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :topics
  resources :replies
  get 'topics/:id/like' => 'topics#like'
  root 'topics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to :controller => 'topics', :action => 'show', :id => @reply.topic_id }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:topic_id, :comment)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @topic = Topic.new
    @reply = Reply.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @reply = Reply.new
    @replies = Reply.where(topic_id:params[:id])
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end
  
  def like
    @topic = Topic.all.find(params[:id])
    @topic.like += 1
    
    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url}
        format.json { head :no_content }
      end
    end
  end


  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to :action => 'index', notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:body, :like)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/replies/_form.html.erb
<%= form_for(reply) do |f| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic_id %>
    <%= f.number_field :topic_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.topic_id %></td>
        <td><%= reply.comment %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @reply.topic_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, id: :topic_body %>
  </div>
  
  <div class="field">
    <%= f.label :like %>
    <%= f.text_field :like, id: :topic_like %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mini Blog</h1>

<table>
  <thead>
    <%= form_for @topic, :url => {:controller => :topics, :action => :create} do |f| %>
      <%= f.text_field :body, :placeholder => '投稿しよう', :size => '80%', :body => 'topic[body]', :id => 'topic_body' %>
      <%= f.submit "投稿する", :name => 'commit', :disable_with => '投稿する' %>
    <% end %>
  </thead>

  <tbody>
    <% @topics.reverse_each do |topic| %>
      <tr>
        <td><%= topic.id %>.</td>
        <td><%= link_to topic.body, topic %></td>
        <td><%= link_to 'いいね', action: 'like', controller: 'topics', id: topic.id  %>:<%= topic.like %></td>
        <td>コメント数:<%= topic.replies.length %></td>
        <td>更新日時:<%= topic.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Mini Blog</h1>

<p>
  <%= @topic.body %>
</p>


<table>
  <thead>
    <%= form_for @reply, :url => {:controller => :replies, :action => :create} do |f| %>
      <%= f.text_field :comment, :placeholder => 'コメントしよう', :size => '80%', :name => 'reply[comment]', :id => 'reply_comment' %>
      <%= f.hidden_field :topic_id, :value => @topic.id %>
      <%= f.submit "コメントする", :name => 'commit', :disable_with => 'コメントする' %>
    <% end %>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.comment %></td>
        <td>更新日時:<%= reply.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', topics_path %>